@echo
@cd/d "C:\XuanZhi\LDPlayer"
@cd/d "D:\XuanZhi\LDPlayer"
@cd/d "E:\XuanZhi\LDPlayer"
@cd/d "F:\XuanZhi\LDPlayer"
@cd/d "Y:\XuanZhi\LDPlayer"
@cd/d "H:\XuanZhi\LDPlayer"
ld.exe -s 0 "mount -o remount,rw /"
ld.exe -s 0 "mount -o remount,rw /system"
ld.exe -s 0 "mount -o remount,rw /data"
ld.exe -s 0 "mount -o remount,rw /data/data"
ld.exe -s 0 "/data/data/com.tencent.ig/files/"
ld.exe -s 0 "busybox mount --bind /root /data/data/com.tencent.ig/files/tss_tmp"
ld.exe -s 0 "mount -o remount,rw /"
ld.exe -s 0 "mount -o remount,rw /system"
ld.exe -s 0 "mount -o remount,rw /data"
ld.exe -s 0 "mount -o remount,rw /data/data"
ld.exe -s 0 "mount -o remount,rw /"
ld.exe -s 0 "mount -o remount,rw /system"
ld.exe -s 0 "mount -o remount,rw /dev"
ld.exe -s 0 "chattr -i /data/data/com.tencent.ig/files/tss_tmp"
ld.exe -s 0 "iptables -F"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/files/tss_tmp"
dnconsole.exe launchex --index 0 --packagename "com.tencent.ig"
ld.exe -s 0 sleep 4
ld.exe -s 0 "pidof com.tencent.ig"
ld.exe -s 0 "mount -o rw,remount /lib"
ld.exe -s 0 "mount -o rw,remount /system"
ld.exe -s 0 "mount -o rw,remount /data/data"
ld.exe -s 0 "mount -o remount,rw /"
ld.exe -s 0 "ls  -l /data/data/com.vng.pubgmobile"
ld.exe -s 0 "for i in $(pidof com.tencent.ig | awk '{print $1}');do busybox mount --bind /proc/2/maps /proc/$i/maps;done;"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/app_bugly"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/cache"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/app_crashrecord"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/code_cache"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/no_backup"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/files"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/shared_prefs"
ld.exe -s 0 "rm -rf /data/data/com.tencent.ig/databases"
ld.exe -s 0 "busybox mount --bind /sbin /system/etc/security/cacerts"
